/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Sistema3 extends javax.swing.JFrame {

    /**
     * Creates new form Sistema3
     */
    public Sistema3() {
         setTitle("Sistema de ecuaciones lineales de 3*3");
        initComponents();
         setLocationRelativeTo(null);
    }
private Double redo(Double N){
        return (Math.rint(N*100)/100);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtX1 = new javax.swing.JTextField();
        txtY1 = new javax.swing.JTextField();
        txtX2 = new javax.swing.JTextField();
        txtY2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblX = new javax.swing.JTextField();
        lblY = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtZ1 = new javax.swing.JTextField();
        txtZ2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtZ3 = new javax.swing.JTextField();
        lblZ = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtC1 = new javax.swing.JTextField();
        txtC2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtX3 = new javax.swing.JTextField();
        txtY3 = new javax.swing.JTextField();
        txtC3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtX1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtX1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtX1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX1KeyTyped(evt);
            }
        });
        getContentPane().add(txtX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, 70));

        txtY1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtY1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtY1KeyReleased(evt);
            }
        });
        getContentPane().add(txtY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 100, 70));

        txtX2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtX2KeyReleased(evt);
            }
        });
        getContentPane().add(txtX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 90, 70));

        txtY2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtY2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtY2KeyReleased(evt);
            }
        });
        getContentPane().add(txtY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 100, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("=");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        lblX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblX.setBorder(javax.swing.BorderFactory.createTitledBorder("VALOR DE \"X\""));
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 480, 60));

        lblY.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblY.setBorder(javax.swing.BorderFactory.createTitledBorder("\"VALOR DE Y\""));
        getContentPane().add(lblY, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 480, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("y");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 96)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("+");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        txtZ1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtZ1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtZ1KeyReleased(evt);
            }
        });
        getContentPane().add(txtZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 100, 70));

        txtZ2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtZ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZ2ActionPerformed(evt);
            }
        });
        txtZ2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtZ2KeyReleased(evt);
            }
        });
        getContentPane().add(txtZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 100, 70));

        jButton1.setBackground(new java.awt.Color(204, 153, 255));
        jButton1.setFont(new java.awt.Font("Forte", 0, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 153));
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 250, 60));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("ScriptC", 0, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 204, 0));
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 250, 60));

        txtZ3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtZ3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtZ3KeyReleased(evt);
            }
        });
        getContentPane().add(txtZ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 100, 60));

        lblZ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblZ.setBorder(javax.swing.BorderFactory.createTitledBorder("\"VALOR DE Z\""));
        getContentPane().add(lblZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 480, 60));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 96)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("+");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        txtC1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        txtC1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtC1KeyReleased(evt);
            }
        });
        getContentPane().add(txtC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 90, 70));

        txtC2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        txtC2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtC2KeyReleased(evt);
            }
        });
        getContentPane().add(txtC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 90, 70));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("x");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 0));
        jButton3.setText("Redondear \"X\" ,\"Y\", \"Z\"");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 250, 60));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("z");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        txtX3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtX3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtX3KeyReleased(evt);
            }
        });
        getContentPane().add(txtX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 90, 70));

        txtY3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtY3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtY3KeyReleased(evt);
            }
        });
        getContentPane().add(txtY3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 100, 70));

        txtC3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        txtC3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtC3KeyReleased(evt);
            }
        });
        getContentPane().add(txtC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 90, 60));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 96)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 51));
        jLabel21.setText("+");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 255));
        jLabel1.setText("Sistema de ecuaciones lineales de 3*3");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 660, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 70));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("x");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 255));
        jLabel23.setText("y");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 96)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 51));
        jLabel24.setText("+");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, 120));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("=");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 255));
        jLabel26.setText("z");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 96)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 51));
        jLabel27.setText("+");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 255));
        jLabel28.setText("x");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 255));
        jLabel29.setText("y");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 96)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 51));
        jLabel30.setText("+");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("=");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 255));
        jLabel32.setText("z");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ufps7.jpg")));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 640));

        jMenu1.setText("Menú");
        jMenu1.add(jSeparator2);

        jMenuItem2.setText("Volver");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Menu p1=new Menu();
        p1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void txtX1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX1KeyReleased
        if(!txtX1.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtX1.setText("");
        }
    }//GEN-LAST:event_txtX1KeyReleased

    private void txtX1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX1KeyTyped

    }//GEN-LAST:event_txtX1KeyTyped

    private void txtY1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtY1KeyReleased
        if(!txtY1.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtY1.setText("");
        }
    }//GEN-LAST:event_txtY1KeyReleased

    private void txtX2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX2KeyReleased
        if(!txtX2.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtX2.setText("");
        }
    }//GEN-LAST:event_txtX2KeyReleased

    private void txtY2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtY2KeyReleased
        if(!txtY2.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtY2.setText("");
        }
    }//GEN-LAST:event_txtY2KeyReleased

    private void txtZ1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZ1KeyReleased
        if(!txtZ1.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtZ1.setText("");
        }
    }//GEN-LAST:event_txtZ1KeyReleased

    private void txtZ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZ2ActionPerformed
        if(!txtZ2.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtZ2.setText("");
        }
    }//GEN-LAST:event_txtZ2ActionPerformed

    private void txtZ2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZ2KeyReleased
        if(!txtZ2.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtZ2.setText("");
        }
    }//GEN-LAST:event_txtZ2KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double x1,x2,x3,y1,y2,y3,c1,c2,c3,z1,z2,z3,xa,xb,ya,dx,dy,yb,za,zb,dz,deta,detb,detc,detg,detafinal,detbfinal,detcfinal;

        if(txtX1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el x1");
        }else if(txtX2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el x2");
        }else if(txtX3.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el x3");
        }else if(txtY1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el y1");
        } if(txtY2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el y2");
        } if(txtY3.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el y3");
        }  else if(txtZ1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el z1");
        } else if(txtZ2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el z2");
        } else if(txtZ3.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el z3");
        }  else if(txtC1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el d1");
        } else if(txtC2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el d2");
        } else if(txtC3.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el d3");

        }else {
            x1=Double.parseDouble(txtX1.getText());
            x2=Double.parseDouble(txtX2.getText());
            x3=Double.parseDouble(txtX3.getText());
            y1=Double.parseDouble(txtY1.getText());
            y2=Double.parseDouble(txtY2.getText());
            y3=Double.parseDouble(txtY3.getText());
            c1=Double.parseDouble(txtC1.getText());
            c2=Double.parseDouble(txtC2.getText());
            c3=Double.parseDouble(txtC3.getText());
            z1=Double.parseDouble(txtZ1.getText());
            z2=Double.parseDouble(txtZ2.getText());
            z3=Double.parseDouble(txtZ3.getText());

            deta=(x3*y2*c1)+(x1*y3*c2)+(x2*y1*c3);
            detb= (x1*y2*c3)+(x2*y3*c1)+(x3*y1*c2);
            detg= detb-deta;
            xa=(z1*y2*c3+z2*y3*c1+z3*y1*c2);
            xb=(z3*y2*c1+z1*y3*c2+z2*y1*c3);
            deta=xa-xb;
            detafinal=deta/detg;
            ya= (x1*z2*c3+x2*z3*c1+x3*z1*c2);
            yb=(x3*z2*c1+x1*z3*c2+x2*z1*c3);
            detb=ya-yb;
            detbfinal=detb/detg;
            za= (x1*y2*z3+x2*y3*z1+x3*y1*z2);
            zb= (x3*y2*z1+x1*y3*z2+x2*y1*z3);
            detc=za-zb;
            detcfinal=detc/detg;
            lblX.setText(detafinal+"");
            lblY.setText(detbfinal+"");
            lblZ.setText(detcfinal+"");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtX1.setText("");
        txtY1.setText("");
        txtX2.setText("");
        txtY2.setText("");
        txtZ1.setText("");
        txtZ2.setText("");
        lblX.setText("");
        lblY.setText("");
        lblZ.setText("");
        txtX3.setText("");
        txtY3.setText("");
        txtZ3.setText("");
        txtC1.setText("");
        txtC2.setText("");
        txtC3.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtZ3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZ3KeyReleased
        if(!txtZ3.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtZ3.setText("");
        }
    }//GEN-LAST:event_txtZ3KeyReleased

    private void txtC1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtC1KeyReleased
        if(!txtC1.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtC1.setText("");
        }
    }//GEN-LAST:event_txtC1KeyReleased

    private void txtC2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtC2KeyReleased
        if(!txtC2.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtC2.setText("");
        }
    }//GEN-LAST:event_txtC2KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double x1,x2,x3,y1,y2,y3,c1,c2,c3,z1,z2,z3,xa,xb,ya,dx,dy,yb,za,zb,dz,deta,detb,detc,detg,detafinal,detbfinal,detcfinal;

        if(txtX1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el x1");
        }else if(txtX2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el x2");
        }else if(txtX3.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el x3");
        }else if(txtY1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el y1");
        } if(txtY2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el y2");
        }else if(txtY3.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el y3");
        }  else if(txtZ1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el z1");
        } else if(txtZ2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltar llenar el z2");

        }else {
            x1=Double.parseDouble(txtX1.getText());
            x2=Double.parseDouble(txtX2.getText());
            x3=Double.parseDouble(txtX3.getText());
            y1=Double.parseDouble(txtY1.getText());
            y2=Double.parseDouble(txtY2.getText());
            y3=Double.parseDouble(txtY3.getText());
            c1=Double.parseDouble(txtC1.getText());
            c2=Double.parseDouble(txtC2.getText());
            c3=Double.parseDouble(txtC3.getText());
            z1=Double.parseDouble(txtZ1.getText());
            z2=Double.parseDouble(txtZ2.getText());
            z3=Double.parseDouble(txtZ3.getText());

            deta=(x3*y2*c1)+(x1*y3*c2)+(x2*y1*c3);
            detb= (x1*y2*c3)+(x2*y3*c1)+(x3*y1*c2);
            detg= detb-deta;
            xa=(z1*y2*c3+z2*y3*c1+z3*y1*c2);
            xb=(z3*y2*c1+z1*y3*c2+z2*y1*c3);
            deta=xa-xb;
            detafinal=deta/detg;
            ya= (x1*z2*c3+x2*z3*c1+x3*z1*c2);
            yb=(x3*z2*c1+x1*z3*c2+x2*z1*c3);
            detb=ya-yb;
            detbfinal=detb/detg;
            za= (x1*y2*z3+x2*y3*z1+x3*y1*z2);
            zb= (x3*y2*z1+x1*y3*z2+x2*y1*z3);
            detc=za-zb;
            detcfinal=detc/detg;

            lblX.setText(+redo(detafinal)+"");
            lblY.setText(+redo(detbfinal)+"");
            lblZ.setText(+redo(detcfinal)+"");

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtX3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX3KeyReleased
        if(!txtX3.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtX3.setText("");
        }
    }//GEN-LAST:event_txtX3KeyReleased

    private void txtY3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtY3KeyReleased
        if(!txtY3.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtY3.setText("");
        }
    }//GEN-LAST:event_txtY3KeyReleased

    private void txtC3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtC3KeyReleased
        if(!txtC3.getText().matches("[0-9-]*")){
            JOptionPane.showMessageDialog(null,"Solo ingrese números");
            txtC3.setText("");
        }
    }//GEN-LAST:event_txtC3KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextField lblX;
    private javax.swing.JTextField lblY;
    private javax.swing.JTextField lblZ;
    private javax.swing.JTextField txtC1;
    private javax.swing.JTextField txtC2;
    private javax.swing.JTextField txtC3;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtX3;
    private javax.swing.JTextField txtY1;
    private javax.swing.JTextField txtY2;
    private javax.swing.JTextField txtY3;
    private javax.swing.JTextField txtZ1;
    private javax.swing.JTextField txtZ2;
    private javax.swing.JTextField txtZ3;
    // End of variables declaration//GEN-END:variables
}
